### ISSUE TITLE
How to run datacite-rest-client

### ISSUE THREAD

**Issue by NhlamuloChauke** [gbif/datacite-rest-client#19]
Hi,

I wanted to test the rest endpoint for datacite using your amazing datacite-rest-client service.

I can do `mvn package`. So what are the steps of running the client in a way that I can even use to test the rest endpoints?

Your response will be highly appreciated.

**Comment by mike-podolskiy90** [comment]
Sorry for the late reply and thank you for contacting us @NhlamuloChauke 
May I ask, what are you going to use the client for?
